'use strict';

const common = require('@lykmapipo/common');

// population options
const POPULATION_MAX_DEPTH = 1;

const POPULATION_DEFAULT = { maxDepth: POPULATION_MAX_DEPTH };

const OPTION_PARTY_AUTOPOPULATE = {
  select: { name: 1, email: 1, mobile: 1, abbreviation: 1 },
  maxDepth: POPULATION_MAX_DEPTH,
};

const OPTION_PERMISSION_AUTOPOPULATE = {
  select: { resource: 1, action: 1, wildcard: 1 },
  maxDepth: POPULATION_MAX_DEPTH,
};

// model names
const MODEL_NAME_PREDEFINE = 'Predefine';
const MODEL_NAME_UNIT = 'Predefine';
const MODEL_NAME_ADMINISTRATIVELEVEL = 'Predefine';
const MODEL_NAME_FEATURETYPE = 'Predefine';
const MODEL_NAME_EVENTINDICATOR = 'Predefine';
const MODEL_NAME_EVENTTOPIC = 'Predefine';
const MODEL_NAME_EVENTLEVEL = 'Predefine';
const MODEL_NAME_EVENTSEVERITY = 'Predefine';
const MODEL_NAME_EVENTCERTAINTY = 'Predefine';
const MODEL_NAME_EVENTSTATUS = 'Predefine';
const MODEL_NAME_EVENTURGENCY = 'Predefine';
const MODEL_NAME_EVENTRESPONSE = 'Predefine';
const MODEL_NAME_PARTYGROUP = 'Predefine';
const MODEL_NAME_PARTYROLE = 'Predefine';
const MODEL_NAME_EVENTGROUP = 'Predefine';
const MODEL_NAME_EVENTTYPE = 'Predefine';
const MODEL_NAME_EVENTFUNCTION = 'Predefine';
const MODEL_NAME_EVENTACTION = 'Predefine';
const MODEL_NAME_EVENTQUESTION = 'Predefine';
const MODEL_NAME_PERMISSION = 'Permission';
const MODEL_NAME_ROLE = 'Predefine';
const MODEL_NAME_ADMINISTRATIVEAREA = 'Predefine';
const MODEL_NAME_PARTY = 'Party';
const MODEL_NAME_FEATURE = 'Predefine';
const MODEL_NAME_EVENTACTIONCATALOGUE = 'Predefine';
const MODEL_NAME_NOTIFICATIONTEMPLATE = 'Predefine';
const MODEL_NAME_EVENT = 'Event';
const MODEL_NAME_EVENTCHANGELOG = 'EventChangeLog';

// collection names
const COLLECTION_NAME_PREDEFINE = 'predefines';
const COLLECTION_NAME_UNIT = 'predefines';
const COLLECTION_NAME_ADMINISTRATIVELEVEL = 'predefines';
const COLLECTION_NAME_FEATURETYPE = 'predefines';
const COLLECTION_NAME_EVENTINDICATOR = 'predefines';
const COLLECTION_NAME_EVENTTOPIC = 'predefines';
const COLLECTION_NAME_EVENTLEVEL = 'predefines';
const COLLECTION_NAME_EVENTSEVERITY = 'predefines';
const COLLECTION_NAME_EVENTCERTAINTY = 'predefines';
const COLLECTION_NAME_EVENTSTATUS = 'predefines';
const COLLECTION_NAME_EVENTURGENCY = 'predefines';
const COLLECTION_NAME_EVENTRESPONSE = 'predefines';
const COLLECTION_NAME_PARTYGROUP = 'predefines';
const COLLECTION_NAME_PARTYROLE = 'predefines';
const COLLECTION_NAME_EVENTGROUP = 'predefines';
const COLLECTION_NAME_EVENTTYPE = 'predefines';
const COLLECTION_NAME_EVENTFUNCTION = 'predefines';
const COLLECTION_NAME_EVENTACTION = 'predefines';
const COLLECTION_NAME_EVENTQUESTION = 'predefines';
const COLLECTION_NAME_PERMISSION = 'permissions';
const COLLECTION_NAME_ROLE = 'predefines';
const COLLECTION_NAME_ADMINISTRATIVEAREA = 'predefines';
const COLLECTION_NAME_PARTY = 'parties';
const COLLECTION_NAME_FEATURE = 'predefines';
const COLLECTION_NAME_EVENTACTIONCATALOGUE = 'predefines';
const COLLECTION_NAME_NOTIFICATIONTEMPLATE = 'predefines';
const COLLECTION_NAME_EVENT = 'events';
const COLLECTION_NAME_EVENTCHANGELOG = 'eventchangelogs';

// predefine namespaces
const PREDEFINE_NAMESPACE_UNIT = 'Unit';
const PREDEFINE_NAMESPACE_ADMINISTRATIVELEVEL = 'AdministrativeLevel';
const PREDEFINE_NAMESPACE_FEATURETYPE = 'FeatureType';
const PREDEFINE_NAMESPACE_EVENTINDICATOR = 'EventIndicator';
const PREDEFINE_NAMESPACE_EVENTTOPIC = 'EventTopic';
const PREDEFINE_NAMESPACE_EVENTLEVEL = 'EventLevel';
const PREDEFINE_NAMESPACE_EVENTSEVERITY = 'EventSeverity';
const PREDEFINE_NAMESPACE_EVENTCERTAINTY = 'EventCertainty';
const PREDEFINE_NAMESPACE_EVENTSTATUS = 'EventStatus';
const PREDEFINE_NAMESPACE_EVENTURGENCY = 'EventUrgency';
const PREDEFINE_NAMESPACE_EVENTRESPONSE = 'EventResponse';
const PREDEFINE_NAMESPACE_PARTYGROUP = 'PartyGroup';
const PREDEFINE_NAMESPACE_PARTYROLE = 'PartyRole';
const PREDEFINE_NAMESPACE_EVENTGROUP = 'EventGroup';
const PREDEFINE_NAMESPACE_EVENTTYPE = 'EventType';
const PREDEFINE_NAMESPACE_EVENTFUNCTION = 'EventFunction';
const PREDEFINE_NAMESPACE_EVENTACTION = 'EventAction';
const PREDEFINE_NAMESPACE_EVENTQUESTION = 'EventQuestion';
const PREDEFINE_NAMESPACE_ROLE = 'Role';
const PREDEFINE_NAMESPACE_ADMINISTRATIVEAREA = 'AdministrativeArea';
const PREDEFINE_NAMESPACE_FEATURE = 'Feature';
const PREDEFINE_NAMESPACE_EVENTACTIONCATALOGUE = 'EventActionCatalogue';
const PREDEFINE_NAMESPACE_NOTIFICATIONTEMPLATE = 'NotificationTemplate';
const PREDEFINE_NAMESPACES = [
  PREDEFINE_NAMESPACE_UNIT,
  PREDEFINE_NAMESPACE_ADMINISTRATIVELEVEL,
  PREDEFINE_NAMESPACE_FEATURETYPE,
  PREDEFINE_NAMESPACE_EVENTINDICATOR,
  PREDEFINE_NAMESPACE_EVENTTOPIC,
  PREDEFINE_NAMESPACE_EVENTLEVEL,
  PREDEFINE_NAMESPACE_EVENTSEVERITY,
  PREDEFINE_NAMESPACE_EVENTCERTAINTY,
  PREDEFINE_NAMESPACE_EVENTSTATUS,
  PREDEFINE_NAMESPACE_EVENTURGENCY,
  PREDEFINE_NAMESPACE_EVENTRESPONSE,
  PREDEFINE_NAMESPACE_PARTYGROUP,
  PREDEFINE_NAMESPACE_PARTYROLE,
  PREDEFINE_NAMESPACE_EVENTGROUP,
  PREDEFINE_NAMESPACE_EVENTTYPE,
  PREDEFINE_NAMESPACE_EVENTFUNCTION,
  PREDEFINE_NAMESPACE_EVENTACTION,
  PREDEFINE_NAMESPACE_EVENTQUESTION,
  PREDEFINE_NAMESPACE_ROLE,
  PREDEFINE_NAMESPACE_ADMINISTRATIVEAREA,
  PREDEFINE_NAMESPACE_FEATURE,
  PREDEFINE_NAMESPACE_EVENTACTIONCATALOGUE,
  PREDEFINE_NAMESPACE_NOTIFICATIONTEMPLATE,
];

// predefine buckets
const PREDEFINE_BUCKET_UNIT = 'units';
const PREDEFINE_BUCKET_ADMINISTRATIVELEVEL = 'administrativelevels';
const PREDEFINE_BUCKET_FEATURETYPE = 'featuretypes';
const PREDEFINE_BUCKET_EVENTINDICATOR = 'eventindicators';
const PREDEFINE_BUCKET_EVENTTOPIC = 'eventtopics';
const PREDEFINE_BUCKET_EVENTLEVEL = 'eventlevels';
const PREDEFINE_BUCKET_EVENTSEVERITY = 'eventseverities';
const PREDEFINE_BUCKET_EVENTCERTAINTY = 'eventcertainties';
const PREDEFINE_BUCKET_EVENTSTATUS = 'eventstatuses';
const PREDEFINE_BUCKET_EVENTURGENCY = 'eventurgencies';
const PREDEFINE_BUCKET_EVENTRESPONSE = 'eventresponses';
const PREDEFINE_BUCKET_PARTYGROUP = 'partygroups';
const PREDEFINE_BUCKET_PARTYROLE = 'partyroles';
const PREDEFINE_BUCKET_EVENTGROUP = 'eventgroups';
const PREDEFINE_BUCKET_EVENTTYPE = 'eventtypes';
const PREDEFINE_BUCKET_EVENTFUNCTION = 'eventfunctions';
const PREDEFINE_BUCKET_EVENTACTION = 'eventactions';
const PREDEFINE_BUCKET_EVENTQUESTION = 'eventquestions';
const PREDEFINE_BUCKET_ROLE = 'role';
const PREDEFINE_BUCKET_ADMINISTRATIVEAREA = 'administrativeareas';
const PREDEFINE_BUCKET_FEATURE = 'features';
const PREDEFINE_BUCKET_EVENTACTIONCATALOGUE = 'eventcatalogues';
const PREDEFINE_BUCKET_NOTIFICATIONTEMPLATE = 'notificationtemplates';
const PREDEFINE_BUCKETS = [
  PREDEFINE_BUCKET_UNIT,
  PREDEFINE_BUCKET_ADMINISTRATIVELEVEL,
  PREDEFINE_BUCKET_FEATURETYPE,
  PREDEFINE_BUCKET_EVENTINDICATOR,
  PREDEFINE_BUCKET_EVENTTOPIC,
  PREDEFINE_BUCKET_EVENTLEVEL,
  PREDEFINE_BUCKET_EVENTSEVERITY,
  PREDEFINE_BUCKET_EVENTCERTAINTY,
  PREDEFINE_BUCKET_EVENTSTATUS,
  PREDEFINE_BUCKET_EVENTURGENCY,
  PREDEFINE_BUCKET_EVENTRESPONSE,
  PREDEFINE_BUCKET_PARTYGROUP,
  PREDEFINE_BUCKET_PARTYROLE,
  PREDEFINE_BUCKET_EVENTGROUP,
  PREDEFINE_BUCKET_EVENTTYPE,
  PREDEFINE_BUCKET_EVENTFUNCTION,
  PREDEFINE_BUCKET_EVENTACTION,
  PREDEFINE_BUCKET_EVENTQUESTION,
  PREDEFINE_BUCKET_ROLE,
  PREDEFINE_BUCKET_ADMINISTRATIVEAREA,
  PREDEFINE_BUCKET_FEATURE,
  PREDEFINE_BUCKET_EVENTACTIONCATALOGUE,
  PREDEFINE_BUCKET_NOTIFICATIONTEMPLATE,
];

// path names
const PATH_NAME_UNIT = 'unit';
const PATH_NAME_ADMINISTRATIVELEVEL = 'level';
const PATH_NAME_FEATURETYPE = 'type';
const PATH_NAME_EVENTINDICATOR = 'indicator';
const PATH_NAME_EVENTTOPIC = 'topic';
const PATH_NAME_EVENTLEVEL = 'level';
const PATH_NAME_EVENTSEVERITY = 'severity';
const PATH_NAME_EVENTCERTAINTY = 'certainty';
const PATH_NAME_EVENTSTATUS = 'status';
const PATH_NAME_EVENTURGENCY = 'urgency';
const PATH_NAME_EVENTRESPONSE = 'response';
const PATH_NAME_PARTYGROUP = 'group';
const PATH_NAME_PARTYGROUPS = 'groups';
const PATH_NAME_PARTYROLE = 'role';
const PATH_NAME_PARTYROLES = 'roles';
const PATH_NAME_EVENTGROUP = 'group';
const PATH_NAME_EVENTGROUPS = 'groups';
const PATH_NAME_EVENTTYPE = 'type';
const PATH_NAME_EVENTFUNCTION = 'function';
const PATH_NAME_EVENTACTION = 'action';
const PATH_NAME_EVENTQUESTION = 'question';
const PATH_NAME_EVENTQUESTION_NEED = 'need';
const PATH_NAME_EVENTQUESTION_EFFECT = 'effect';
const PATH_NAME_PERMISSIONS = 'permissions';
const PATH_NAME_ROLE = 'role';
const PATH_NAME_ROLES = 'roles';
const PATH_NAME_ADMINISTRATIVEAREA = 'area';
const PATH_NAME_ADMINISTRATIVEAREAS = 'areas';
const PATH_NAME_PARTY = 'party';
const PATH_NAME_PARTY_FOCAL = 'focal';
const PATH_NAME_PARTY_FOCALS = 'focals';
const PATH_NAME_PARTY_AGENCY = 'agency';
const PATH_NAME_PARTY_AGENCIES = 'agencies';
const PATH_NAME_PARTY_CUSTODIAN = 'custodian';
const PATH_NAME_PARTY_CUSTODIANS = 'custodians';
const PATH_NAME_FEATURE = 'feature';
const PATH_NAME_NOTIFICATIONTEMPLATE = 'template';
const PATH_NAME_EVENT = 'event';
const PATH_NAME_EVENTCHANGELOG = 'changelog';
const PATH_NAME_EVENTCHANGELOGS = 'changelogs';

// predefine defaults(name, number etc)
const PREDEFINE_UNIT_NAME = undefined;
const PREDEFINE_ADMINISTRATIVELEVEL_NAME = undefined;
const PREDEFINE_FEATURETYPE_NAME = undefined;
const PREDEFINE_EVENTINDICATOR_NAME = undefined;
const PREDEFINE_EVENTTOPIC_NAME = undefined;
const PREDEFINE_EVENTLEVEL_NAME = 'White';
const PREDEFINE_EVENTSEVERITY_NAME = 'Unknown';
const PREDEFINE_EVENTCERTAINTY_NAME = 'Unknown';
const PREDEFINE_EVENTSTATUS_NAME = 'Actual';
const PREDEFINE_EVENTURGENCY_NAME = 'Unknown';
const PREDEFINE_EVENTRESPONSE_NAME = 'None';
const PREDEFINE_PARTYGROUP_NAME = 'Unknown';
const PREDEFINE_PARTYROLE_NAME = 'Unknown';
const PREDEFINE_EVENTGROUP_NAME = undefined;
const PREDEFINE_EVENTTYPE_NAME = undefined;
const PREDEFINE_EVENTFUNCTION_NAME = undefined;
const PREDEFINE_EVENTACTION_NAME = undefined;
const PREDEFINE_EVENTQUESTION_NAME = undefined;
const PREDEFINE_ADMINISTRATIVEAREA_NAME = undefined;
const PREDEFINE_FEATURE_NAME = undefined;
const PREDEFINE_EVENTACTIONCATALOGUE_NAME = undefined;
const PREDEFINE_NOTIFICATIONTEMPLATE_NAME = undefined;
const PREDEFINE_DEFAULTS = {
  [PREDEFINE_NAMESPACE_UNIT]: PREDEFINE_UNIT_NAME,
  [PREDEFINE_NAMESPACE_ADMINISTRATIVELEVEL]: PREDEFINE_ADMINISTRATIVELEVEL_NAME,
  [PREDEFINE_NAMESPACE_FEATURETYPE]: PREDEFINE_FEATURETYPE_NAME,
  [PREDEFINE_NAMESPACE_EVENTINDICATOR]: PREDEFINE_EVENTINDICATOR_NAME,
  [PREDEFINE_NAMESPACE_EVENTTOPIC]: PREDEFINE_EVENTTOPIC_NAME,
  [PREDEFINE_NAMESPACE_EVENTLEVEL]: PREDEFINE_EVENTLEVEL_NAME,
  [PREDEFINE_NAMESPACE_EVENTSEVERITY]: PREDEFINE_EVENTSEVERITY_NAME,
  [PREDEFINE_NAMESPACE_EVENTCERTAINTY]: PREDEFINE_EVENTCERTAINTY_NAME,
  [PREDEFINE_NAMESPACE_EVENTSTATUS]: PREDEFINE_EVENTSTATUS_NAME,
  [PREDEFINE_NAMESPACE_EVENTURGENCY]: PREDEFINE_EVENTURGENCY_NAME,
  [PREDEFINE_NAMESPACE_EVENTRESPONSE]: PREDEFINE_EVENTRESPONSE_NAME,
  [PREDEFINE_NAMESPACE_PARTYGROUP]: PREDEFINE_PARTYGROUP_NAME,
  [PREDEFINE_NAMESPACE_PARTYROLE]: PREDEFINE_PARTYROLE_NAME,
  [PREDEFINE_NAMESPACE_EVENTGROUP]: PREDEFINE_EVENTGROUP_NAME,
  [PREDEFINE_NAMESPACE_EVENTTYPE]: PREDEFINE_EVENTTYPE_NAME,
  [PREDEFINE_NAMESPACE_EVENTFUNCTION]: PREDEFINE_EVENTFUNCTION_NAME,
  [PREDEFINE_NAMESPACE_EVENTACTION]: PREDEFINE_EVENTACTION_NAME,
  [PREDEFINE_NAMESPACE_EVENTQUESTION]: PREDEFINE_EVENTQUESTION_NAME,
  [PREDEFINE_NAMESPACE_ADMINISTRATIVEAREA]: PREDEFINE_ADMINISTRATIVEAREA_NAME,
  [PREDEFINE_NAMESPACE_FEATURETYPE]: PREDEFINE_FEATURE_NAME,
  [PREDEFINE_NAMESPACE_EVENTACTIONCATALOGUE]: PREDEFINE_EVENTACTIONCATALOGUE_NAME,
  [PREDEFINE_NAMESPACE_NOTIFICATIONTEMPLATE]: PREDEFINE_NOTIFICATIONTEMPLATE_NAME,
};

// predefine relations
const PREDEFINE_RELATIONS = {
  parent: { ref: MODEL_NAME_PREDEFINE, namespace: PREDEFINE_NAMESPACES },
  permissions: {
    ref: MODEL_NAME_PERMISSION,
    array: true,
    autopopulate: OPTION_PERMISSION_AUTOPOPULATE,
  },
  roles: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: PREDEFINE_NAMESPACE_PARTYROLE,
    array: true,
  },
  groups: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: PREDEFINE_NAMESPACE_PARTYGROUP,
    array: true,
  },
  group: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: PREDEFINE_NAMESPACE_EVENTGROUP,
  },
  type: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: [PREDEFINE_NAMESPACE_EVENTTYPE, PREDEFINE_NAMESPACE_FEATURETYPE],
  },
  function: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: PREDEFINE_NAMESPACE_EVENTFUNCTION,
  },
  action: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: PREDEFINE_NAMESPACE_EVENTACTION,
  },
  level: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: [
      PREDEFINE_NAMESPACE_ADMINISTRATIVELEVEL,
      PREDEFINE_NAMESPACE_EVENTLEVEL,
    ],
  },
  area: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: PREDEFINE_NAMESPACE_ADMINISTRATIVEAREA,
  },
  indicator: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: PREDEFINE_NAMESPACE_EVENTINDICATOR,
  },
  topic: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: PREDEFINE_NAMESPACE_EVENTTOPIC,
  },
  unit: { ref: MODEL_NAME_PREDEFINE, namespace: PREDEFINE_NAMESPACE_UNIT },
  agencies: {
    ref: MODEL_NAME_PARTY,
    array: true,
    autopopulate: OPTION_PARTY_AUTOPOPULATE,
  },
  focals: {
    ref: MODEL_NAME_PARTY,
    array: true,
    autopopulate: OPTION_PARTY_AUTOPOPULATE,
  },
  custodians: {
    ref: MODEL_NAME_PARTY,
    array: true,
    autopopulate: OPTION_PARTY_AUTOPOPULATE,
  },
};

// party relations
const PARTY_RELATIONS = {
  party: { ref: MODEL_NAME_PARTY },
  agency: { ref: MODEL_NAME_PARTY, path: 'party' },
  group: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: PREDEFINE_NAMESPACE_PARTYGROUP,
  },
  area: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: PREDEFINE_NAMESPACE_ADMINISTRATIVEAREA,
  },
  role: { ref: MODEL_NAME_PREDEFINE, namespace: PREDEFINE_NAMESPACE_PARTYROLE },
};

// event relations
const EVENT_RELATIONS = {
  group: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: PREDEFINE_NAMESPACE_EVENTGROUP,
  },
  type: { ref: MODEL_NAME_PREDEFINE, namespace: PREDEFINE_NAMESPACE_EVENTTYPE },
  level: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: PREDEFINE_NAMESPACE_EVENTLEVEL,
  },
  severity: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: PREDEFINE_NAMESPACE_EVENTSEVERITY,
  },
  certainty: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: PREDEFINE_NAMESPACE_EVENTCERTAINTY,
  },
  status: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: PREDEFINE_NAMESPACE_EVENTSTATUS,
  },
  urgency: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: PREDEFINE_NAMESPACE_EVENTURGENCY,
  },
  response: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: PREDEFINE_NAMESPACE_EVENTRESPONSE,
  },
  areas: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: PREDEFINE_NAMESPACE_ADMINISTRATIVEAREA,
    array: true,
  },
};

// event changelog relations
const EVENT_CHANGELOG_RELATIONS = {
  initiator: { ref: MODEL_NAME_PARTY },
  verifier: { ref: MODEL_NAME_PARTY },
  group: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: PREDEFINE_NAMESPACE_EVENTGROUP,
  },
  type: { ref: MODEL_NAME_PREDEFINE, namespace: PREDEFINE_NAMESPACE_EVENTTYPE },
  event: { ref: MODEL_NAME_EVENT },
  function: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: PREDEFINE_NAMESPACE_EVENTFUNCTION,
  },
  action: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: PREDEFINE_NAMESPACE_EVENTACTION,
  },
  catalogue: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: PREDEFINE_NAMESPACE_EVENTACTIONCATALOGUE,
  },
  indicator: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: PREDEFINE_NAMESPACE_EVENTINDICATOR,
  },
  topic: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: PREDEFINE_NAMESPACE_EVENTTOPIC,
  },
  question: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: PREDEFINE_NAMESPACE_EVENTQUESTION,
  },
  need: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: PREDEFINE_NAMESPACE_EVENTQUESTION,
  },
  effect: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: PREDEFINE_NAMESPACE_EVENTQUESTION,
  },
  areas: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: PREDEFINE_NAMESPACE_ADMINISTRATIVEAREA,
    array: true,
  },
  groups: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: PREDEFINE_NAMESPACE_PARTYGROUP,
    array: true,
  },
  roles: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: PREDEFINE_NAMESPACE_PARTYROLE,
    array: true,
  },
  agencies: { ref: MODEL_NAME_PARTY, array: true },
  focals: { ref: MODEL_NAME_PARTY, array: true },
  unit: { ref: MODEL_NAME_PREDEFINE, namespace: PREDEFINE_NAMESPACE_UNIT },
  template: {
    ref: MODEL_NAME_PREDEFINE,
    namespace: PREDEFINE_NAMESPACE_NOTIFICATIONTEMPLATE,
  },
};

// setup env
process.env.PREDEFINE_NAMESPACES = common.join(PREDEFINE_NAMESPACES, ',');
process.env.PREDEFINE_RELATIONS_IGNORED = common.join(PREDEFINE_NAMESPACES, ',');
process.env.PREDEFINE_RELATIONS = common.stringify(PREDEFINE_RELATIONS);

exports.COLLECTION_NAME_ADMINISTRATIVEAREA = COLLECTION_NAME_ADMINISTRATIVEAREA;
exports.COLLECTION_NAME_ADMINISTRATIVELEVEL = COLLECTION_NAME_ADMINISTRATIVELEVEL;
exports.COLLECTION_NAME_EVENT = COLLECTION_NAME_EVENT;
exports.COLLECTION_NAME_EVENTACTION = COLLECTION_NAME_EVENTACTION;
exports.COLLECTION_NAME_EVENTACTIONCATALOGUE = COLLECTION_NAME_EVENTACTIONCATALOGUE;
exports.COLLECTION_NAME_EVENTCERTAINTY = COLLECTION_NAME_EVENTCERTAINTY;
exports.COLLECTION_NAME_EVENTCHANGELOG = COLLECTION_NAME_EVENTCHANGELOG;
exports.COLLECTION_NAME_EVENTFUNCTION = COLLECTION_NAME_EVENTFUNCTION;
exports.COLLECTION_NAME_EVENTGROUP = COLLECTION_NAME_EVENTGROUP;
exports.COLLECTION_NAME_EVENTINDICATOR = COLLECTION_NAME_EVENTINDICATOR;
exports.COLLECTION_NAME_EVENTLEVEL = COLLECTION_NAME_EVENTLEVEL;
exports.COLLECTION_NAME_EVENTQUESTION = COLLECTION_NAME_EVENTQUESTION;
exports.COLLECTION_NAME_EVENTRESPONSE = COLLECTION_NAME_EVENTRESPONSE;
exports.COLLECTION_NAME_EVENTSEVERITY = COLLECTION_NAME_EVENTSEVERITY;
exports.COLLECTION_NAME_EVENTSTATUS = COLLECTION_NAME_EVENTSTATUS;
exports.COLLECTION_NAME_EVENTTOPIC = COLLECTION_NAME_EVENTTOPIC;
exports.COLLECTION_NAME_EVENTTYPE = COLLECTION_NAME_EVENTTYPE;
exports.COLLECTION_NAME_EVENTURGENCY = COLLECTION_NAME_EVENTURGENCY;
exports.COLLECTION_NAME_FEATURE = COLLECTION_NAME_FEATURE;
exports.COLLECTION_NAME_FEATURETYPE = COLLECTION_NAME_FEATURETYPE;
exports.COLLECTION_NAME_NOTIFICATIONTEMPLATE = COLLECTION_NAME_NOTIFICATIONTEMPLATE;
exports.COLLECTION_NAME_PARTY = COLLECTION_NAME_PARTY;
exports.COLLECTION_NAME_PARTYGROUP = COLLECTION_NAME_PARTYGROUP;
exports.COLLECTION_NAME_PARTYROLE = COLLECTION_NAME_PARTYROLE;
exports.COLLECTION_NAME_PERMISSION = COLLECTION_NAME_PERMISSION;
exports.COLLECTION_NAME_PREDEFINE = COLLECTION_NAME_PREDEFINE;
exports.COLLECTION_NAME_ROLE = COLLECTION_NAME_ROLE;
exports.COLLECTION_NAME_UNIT = COLLECTION_NAME_UNIT;
exports.EVENT_CHANGELOG_RELATIONS = EVENT_CHANGELOG_RELATIONS;
exports.EVENT_RELATIONS = EVENT_RELATIONS;
exports.MODEL_NAME_ADMINISTRATIVEAREA = MODEL_NAME_ADMINISTRATIVEAREA;
exports.MODEL_NAME_ADMINISTRATIVELEVEL = MODEL_NAME_ADMINISTRATIVELEVEL;
exports.MODEL_NAME_EVENT = MODEL_NAME_EVENT;
exports.MODEL_NAME_EVENTACTION = MODEL_NAME_EVENTACTION;
exports.MODEL_NAME_EVENTACTIONCATALOGUE = MODEL_NAME_EVENTACTIONCATALOGUE;
exports.MODEL_NAME_EVENTCERTAINTY = MODEL_NAME_EVENTCERTAINTY;
exports.MODEL_NAME_EVENTCHANGELOG = MODEL_NAME_EVENTCHANGELOG;
exports.MODEL_NAME_EVENTFUNCTION = MODEL_NAME_EVENTFUNCTION;
exports.MODEL_NAME_EVENTGROUP = MODEL_NAME_EVENTGROUP;
exports.MODEL_NAME_EVENTINDICATOR = MODEL_NAME_EVENTINDICATOR;
exports.MODEL_NAME_EVENTLEVEL = MODEL_NAME_EVENTLEVEL;
exports.MODEL_NAME_EVENTQUESTION = MODEL_NAME_EVENTQUESTION;
exports.MODEL_NAME_EVENTRESPONSE = MODEL_NAME_EVENTRESPONSE;
exports.MODEL_NAME_EVENTSEVERITY = MODEL_NAME_EVENTSEVERITY;
exports.MODEL_NAME_EVENTSTATUS = MODEL_NAME_EVENTSTATUS;
exports.MODEL_NAME_EVENTTOPIC = MODEL_NAME_EVENTTOPIC;
exports.MODEL_NAME_EVENTTYPE = MODEL_NAME_EVENTTYPE;
exports.MODEL_NAME_EVENTURGENCY = MODEL_NAME_EVENTURGENCY;
exports.MODEL_NAME_FEATURE = MODEL_NAME_FEATURE;
exports.MODEL_NAME_FEATURETYPE = MODEL_NAME_FEATURETYPE;
exports.MODEL_NAME_NOTIFICATIONTEMPLATE = MODEL_NAME_NOTIFICATIONTEMPLATE;
exports.MODEL_NAME_PARTY = MODEL_NAME_PARTY;
exports.MODEL_NAME_PARTYGROUP = MODEL_NAME_PARTYGROUP;
exports.MODEL_NAME_PARTYROLE = MODEL_NAME_PARTYROLE;
exports.MODEL_NAME_PERMISSION = MODEL_NAME_PERMISSION;
exports.MODEL_NAME_PREDEFINE = MODEL_NAME_PREDEFINE;
exports.MODEL_NAME_ROLE = MODEL_NAME_ROLE;
exports.MODEL_NAME_UNIT = MODEL_NAME_UNIT;
exports.OPTION_PARTY_AUTOPOPULATE = OPTION_PARTY_AUTOPOPULATE;
exports.OPTION_PERMISSION_AUTOPOPULATE = OPTION_PERMISSION_AUTOPOPULATE;
exports.PARTY_RELATIONS = PARTY_RELATIONS;
exports.PATH_NAME_ADMINISTRATIVEAREA = PATH_NAME_ADMINISTRATIVEAREA;
exports.PATH_NAME_ADMINISTRATIVEAREAS = PATH_NAME_ADMINISTRATIVEAREAS;
exports.PATH_NAME_ADMINISTRATIVELEVEL = PATH_NAME_ADMINISTRATIVELEVEL;
exports.PATH_NAME_EVENT = PATH_NAME_EVENT;
exports.PATH_NAME_EVENTACTION = PATH_NAME_EVENTACTION;
exports.PATH_NAME_EVENTCERTAINTY = PATH_NAME_EVENTCERTAINTY;
exports.PATH_NAME_EVENTCHANGELOG = PATH_NAME_EVENTCHANGELOG;
exports.PATH_NAME_EVENTCHANGELOGS = PATH_NAME_EVENTCHANGELOGS;
exports.PATH_NAME_EVENTFUNCTION = PATH_NAME_EVENTFUNCTION;
exports.PATH_NAME_EVENTGROUP = PATH_NAME_EVENTGROUP;
exports.PATH_NAME_EVENTGROUPS = PATH_NAME_EVENTGROUPS;
exports.PATH_NAME_EVENTINDICATOR = PATH_NAME_EVENTINDICATOR;
exports.PATH_NAME_EVENTLEVEL = PATH_NAME_EVENTLEVEL;
exports.PATH_NAME_EVENTQUESTION = PATH_NAME_EVENTQUESTION;
exports.PATH_NAME_EVENTQUESTION_EFFECT = PATH_NAME_EVENTQUESTION_EFFECT;
exports.PATH_NAME_EVENTQUESTION_NEED = PATH_NAME_EVENTQUESTION_NEED;
exports.PATH_NAME_EVENTRESPONSE = PATH_NAME_EVENTRESPONSE;
exports.PATH_NAME_EVENTSEVERITY = PATH_NAME_EVENTSEVERITY;
exports.PATH_NAME_EVENTSTATUS = PATH_NAME_EVENTSTATUS;
exports.PATH_NAME_EVENTTOPIC = PATH_NAME_EVENTTOPIC;
exports.PATH_NAME_EVENTTYPE = PATH_NAME_EVENTTYPE;
exports.PATH_NAME_EVENTURGENCY = PATH_NAME_EVENTURGENCY;
exports.PATH_NAME_FEATURE = PATH_NAME_FEATURE;
exports.PATH_NAME_FEATURETYPE = PATH_NAME_FEATURETYPE;
exports.PATH_NAME_NOTIFICATIONTEMPLATE = PATH_NAME_NOTIFICATIONTEMPLATE;
exports.PATH_NAME_PARTY = PATH_NAME_PARTY;
exports.PATH_NAME_PARTYGROUP = PATH_NAME_PARTYGROUP;
exports.PATH_NAME_PARTYGROUPS = PATH_NAME_PARTYGROUPS;
exports.PATH_NAME_PARTYROLE = PATH_NAME_PARTYROLE;
exports.PATH_NAME_PARTYROLES = PATH_NAME_PARTYROLES;
exports.PATH_NAME_PARTY_AGENCIES = PATH_NAME_PARTY_AGENCIES;
exports.PATH_NAME_PARTY_AGENCY = PATH_NAME_PARTY_AGENCY;
exports.PATH_NAME_PARTY_CUSTODIAN = PATH_NAME_PARTY_CUSTODIAN;
exports.PATH_NAME_PARTY_CUSTODIANS = PATH_NAME_PARTY_CUSTODIANS;
exports.PATH_NAME_PARTY_FOCAL = PATH_NAME_PARTY_FOCAL;
exports.PATH_NAME_PARTY_FOCALS = PATH_NAME_PARTY_FOCALS;
exports.PATH_NAME_PERMISSIONS = PATH_NAME_PERMISSIONS;
exports.PATH_NAME_ROLE = PATH_NAME_ROLE;
exports.PATH_NAME_ROLES = PATH_NAME_ROLES;
exports.PATH_NAME_UNIT = PATH_NAME_UNIT;
exports.POPULATION_DEFAULT = POPULATION_DEFAULT;
exports.POPULATION_MAX_DEPTH = POPULATION_MAX_DEPTH;
exports.PREDEFINE_ADMINISTRATIVEAREA_NAME = PREDEFINE_ADMINISTRATIVEAREA_NAME;
exports.PREDEFINE_ADMINISTRATIVELEVEL_NAME = PREDEFINE_ADMINISTRATIVELEVEL_NAME;
exports.PREDEFINE_BUCKETS = PREDEFINE_BUCKETS;
exports.PREDEFINE_BUCKET_ADMINISTRATIVEAREA = PREDEFINE_BUCKET_ADMINISTRATIVEAREA;
exports.PREDEFINE_BUCKET_ADMINISTRATIVELEVEL = PREDEFINE_BUCKET_ADMINISTRATIVELEVEL;
exports.PREDEFINE_BUCKET_EVENTACTION = PREDEFINE_BUCKET_EVENTACTION;
exports.PREDEFINE_BUCKET_EVENTACTIONCATALOGUE = PREDEFINE_BUCKET_EVENTACTIONCATALOGUE;
exports.PREDEFINE_BUCKET_EVENTCERTAINTY = PREDEFINE_BUCKET_EVENTCERTAINTY;
exports.PREDEFINE_BUCKET_EVENTFUNCTION = PREDEFINE_BUCKET_EVENTFUNCTION;
exports.PREDEFINE_BUCKET_EVENTGROUP = PREDEFINE_BUCKET_EVENTGROUP;
exports.PREDEFINE_BUCKET_EVENTINDICATOR = PREDEFINE_BUCKET_EVENTINDICATOR;
exports.PREDEFINE_BUCKET_EVENTLEVEL = PREDEFINE_BUCKET_EVENTLEVEL;
exports.PREDEFINE_BUCKET_EVENTQUESTION = PREDEFINE_BUCKET_EVENTQUESTION;
exports.PREDEFINE_BUCKET_EVENTRESPONSE = PREDEFINE_BUCKET_EVENTRESPONSE;
exports.PREDEFINE_BUCKET_EVENTSEVERITY = PREDEFINE_BUCKET_EVENTSEVERITY;
exports.PREDEFINE_BUCKET_EVENTSTATUS = PREDEFINE_BUCKET_EVENTSTATUS;
exports.PREDEFINE_BUCKET_EVENTTOPIC = PREDEFINE_BUCKET_EVENTTOPIC;
exports.PREDEFINE_BUCKET_EVENTTYPE = PREDEFINE_BUCKET_EVENTTYPE;
exports.PREDEFINE_BUCKET_EVENTURGENCY = PREDEFINE_BUCKET_EVENTURGENCY;
exports.PREDEFINE_BUCKET_FEATURE = PREDEFINE_BUCKET_FEATURE;
exports.PREDEFINE_BUCKET_FEATURETYPE = PREDEFINE_BUCKET_FEATURETYPE;
exports.PREDEFINE_BUCKET_NOTIFICATIONTEMPLATE = PREDEFINE_BUCKET_NOTIFICATIONTEMPLATE;
exports.PREDEFINE_BUCKET_PARTYGROUP = PREDEFINE_BUCKET_PARTYGROUP;
exports.PREDEFINE_BUCKET_PARTYROLE = PREDEFINE_BUCKET_PARTYROLE;
exports.PREDEFINE_BUCKET_ROLE = PREDEFINE_BUCKET_ROLE;
exports.PREDEFINE_BUCKET_UNIT = PREDEFINE_BUCKET_UNIT;
exports.PREDEFINE_DEFAULTS = PREDEFINE_DEFAULTS;
exports.PREDEFINE_EVENTACTIONCATALOGUE_NAME = PREDEFINE_EVENTACTIONCATALOGUE_NAME;
exports.PREDEFINE_EVENTACTION_NAME = PREDEFINE_EVENTACTION_NAME;
exports.PREDEFINE_EVENTCERTAINTY_NAME = PREDEFINE_EVENTCERTAINTY_NAME;
exports.PREDEFINE_EVENTFUNCTION_NAME = PREDEFINE_EVENTFUNCTION_NAME;
exports.PREDEFINE_EVENTGROUP_NAME = PREDEFINE_EVENTGROUP_NAME;
exports.PREDEFINE_EVENTINDICATOR_NAME = PREDEFINE_EVENTINDICATOR_NAME;
exports.PREDEFINE_EVENTLEVEL_NAME = PREDEFINE_EVENTLEVEL_NAME;
exports.PREDEFINE_EVENTQUESTION_NAME = PREDEFINE_EVENTQUESTION_NAME;
exports.PREDEFINE_EVENTRESPONSE_NAME = PREDEFINE_EVENTRESPONSE_NAME;
exports.PREDEFINE_EVENTSEVERITY_NAME = PREDEFINE_EVENTSEVERITY_NAME;
exports.PREDEFINE_EVENTSTATUS_NAME = PREDEFINE_EVENTSTATUS_NAME;
exports.PREDEFINE_EVENTTOPIC_NAME = PREDEFINE_EVENTTOPIC_NAME;
exports.PREDEFINE_EVENTTYPE_NAME = PREDEFINE_EVENTTYPE_NAME;
exports.PREDEFINE_EVENTURGENCY_NAME = PREDEFINE_EVENTURGENCY_NAME;
exports.PREDEFINE_FEATURETYPE_NAME = PREDEFINE_FEATURETYPE_NAME;
exports.PREDEFINE_FEATURE_NAME = PREDEFINE_FEATURE_NAME;
exports.PREDEFINE_NAMESPACES = PREDEFINE_NAMESPACES;
exports.PREDEFINE_NAMESPACE_ADMINISTRATIVEAREA = PREDEFINE_NAMESPACE_ADMINISTRATIVEAREA;
exports.PREDEFINE_NAMESPACE_ADMINISTRATIVELEVEL = PREDEFINE_NAMESPACE_ADMINISTRATIVELEVEL;
exports.PREDEFINE_NAMESPACE_EVENTACTION = PREDEFINE_NAMESPACE_EVENTACTION;
exports.PREDEFINE_NAMESPACE_EVENTACTIONCATALOGUE = PREDEFINE_NAMESPACE_EVENTACTIONCATALOGUE;
exports.PREDEFINE_NAMESPACE_EVENTCERTAINTY = PREDEFINE_NAMESPACE_EVENTCERTAINTY;
exports.PREDEFINE_NAMESPACE_EVENTFUNCTION = PREDEFINE_NAMESPACE_EVENTFUNCTION;
exports.PREDEFINE_NAMESPACE_EVENTGROUP = PREDEFINE_NAMESPACE_EVENTGROUP;
exports.PREDEFINE_NAMESPACE_EVENTINDICATOR = PREDEFINE_NAMESPACE_EVENTINDICATOR;
exports.PREDEFINE_NAMESPACE_EVENTLEVEL = PREDEFINE_NAMESPACE_EVENTLEVEL;
exports.PREDEFINE_NAMESPACE_EVENTQUESTION = PREDEFINE_NAMESPACE_EVENTQUESTION;
exports.PREDEFINE_NAMESPACE_EVENTRESPONSE = PREDEFINE_NAMESPACE_EVENTRESPONSE;
exports.PREDEFINE_NAMESPACE_EVENTSEVERITY = PREDEFINE_NAMESPACE_EVENTSEVERITY;
exports.PREDEFINE_NAMESPACE_EVENTSTATUS = PREDEFINE_NAMESPACE_EVENTSTATUS;
exports.PREDEFINE_NAMESPACE_EVENTTOPIC = PREDEFINE_NAMESPACE_EVENTTOPIC;
exports.PREDEFINE_NAMESPACE_EVENTTYPE = PREDEFINE_NAMESPACE_EVENTTYPE;
exports.PREDEFINE_NAMESPACE_EVENTURGENCY = PREDEFINE_NAMESPACE_EVENTURGENCY;
exports.PREDEFINE_NAMESPACE_FEATURE = PREDEFINE_NAMESPACE_FEATURE;
exports.PREDEFINE_NAMESPACE_FEATURETYPE = PREDEFINE_NAMESPACE_FEATURETYPE;
exports.PREDEFINE_NAMESPACE_NOTIFICATIONTEMPLATE = PREDEFINE_NAMESPACE_NOTIFICATIONTEMPLATE;
exports.PREDEFINE_NAMESPACE_PARTYGROUP = PREDEFINE_NAMESPACE_PARTYGROUP;
exports.PREDEFINE_NAMESPACE_PARTYROLE = PREDEFINE_NAMESPACE_PARTYROLE;
exports.PREDEFINE_NAMESPACE_ROLE = PREDEFINE_NAMESPACE_ROLE;
exports.PREDEFINE_NAMESPACE_UNIT = PREDEFINE_NAMESPACE_UNIT;
exports.PREDEFINE_NOTIFICATIONTEMPLATE_NAME = PREDEFINE_NOTIFICATIONTEMPLATE_NAME;
exports.PREDEFINE_PARTYGROUP_NAME = PREDEFINE_PARTYGROUP_NAME;
exports.PREDEFINE_PARTYROLE_NAME = PREDEFINE_PARTYROLE_NAME;
exports.PREDEFINE_RELATIONS = PREDEFINE_RELATIONS;
exports.PREDEFINE_UNIT_NAME = PREDEFINE_UNIT_NAME;
