'use strict';

// model names
const MODEL_NAME_UNIT = 'Predefine';
const MODEL_NAME_ADMINISTRATIVELEVEL = 'Predefine';
const MODEL_NAME_FEATURETYPE = 'Predefine';
const MODEL_NAME_EVENTINDICATOR = 'Predefine';
const MODEL_NAME_EVENTSEVERITY = 'Predefine';
const MODEL_NAME_EVENTCERTAINTY = 'Predefine';
const MODEL_NAME_PARTYGROUP = 'Predefine';
const MODEL_NAME_PARTYROLE = 'Predefine';
const MODEL_NAME_EVENTGROUP = 'Predefine';
const MODEL_NAME_EVENTTYPE = 'Predefine';
const MODEL_NAME_EVENTFUNCTION = 'Predefine';
const MODEL_NAME_EVENTACTION = 'Predefine';
const MODEL_NAME_EVENTQUESTION = 'Predefine';
const MODEL_NAME_EVENTCATALOGUE = 'Predefine';
const MODEL_NAME_NOTIFICATIONTEMPLATE = 'Predefine';
const MODEL_NAME_PARTY = 'Party';
const MODEL_NAME_PERMISSION = 'Permission';
const MODEL_NAME_PREDEFINE = 'Predefine';
const MODEL_NAME_ROLE = 'Predefine';
const MODEL_NAME_EVENT = 'Event';
const MODEL_NAME_EVENT_CHANGELOG = 'EventChangeLog';

// collection names
const COLLECTION_NAME_EVENT = 'events';

// path names
const PATH_NAME_EVENT = 'event';

// pedefine namespaces
const PREDEFINE_NAMESPACE_UNIT = 'Unit';

// predefine buckets
const PREDEFINE_BUCKET_UNIT = 'units';

// population options
const POPULATION_MAX_DEPTH = 1;
const POPULATION_DEFAULT = { maxDepth: POPULATION_MAX_DEPTH };

exports.COLLECTION_NAME_EVENT = COLLECTION_NAME_EVENT;
exports.MODEL_NAME_ADMINISTRATIVELEVEL = MODEL_NAME_ADMINISTRATIVELEVEL;
exports.MODEL_NAME_EVENT = MODEL_NAME_EVENT;
exports.MODEL_NAME_EVENTACTION = MODEL_NAME_EVENTACTION;
exports.MODEL_NAME_EVENTCATALOGUE = MODEL_NAME_EVENTCATALOGUE;
exports.MODEL_NAME_EVENTCERTAINTY = MODEL_NAME_EVENTCERTAINTY;
exports.MODEL_NAME_EVENTFUNCTION = MODEL_NAME_EVENTFUNCTION;
exports.MODEL_NAME_EVENTGROUP = MODEL_NAME_EVENTGROUP;
exports.MODEL_NAME_EVENTINDICATOR = MODEL_NAME_EVENTINDICATOR;
exports.MODEL_NAME_EVENTQUESTION = MODEL_NAME_EVENTQUESTION;
exports.MODEL_NAME_EVENTSEVERITY = MODEL_NAME_EVENTSEVERITY;
exports.MODEL_NAME_EVENTTYPE = MODEL_NAME_EVENTTYPE;
exports.MODEL_NAME_EVENT_CHANGELOG = MODEL_NAME_EVENT_CHANGELOG;
exports.MODEL_NAME_FEATURETYPE = MODEL_NAME_FEATURETYPE;
exports.MODEL_NAME_NOTIFICATIONTEMPLATE = MODEL_NAME_NOTIFICATIONTEMPLATE;
exports.MODEL_NAME_PARTY = MODEL_NAME_PARTY;
exports.MODEL_NAME_PARTYGROUP = MODEL_NAME_PARTYGROUP;
exports.MODEL_NAME_PARTYROLE = MODEL_NAME_PARTYROLE;
exports.MODEL_NAME_PERMISSION = MODEL_NAME_PERMISSION;
exports.MODEL_NAME_PREDEFINE = MODEL_NAME_PREDEFINE;
exports.MODEL_NAME_ROLE = MODEL_NAME_ROLE;
exports.MODEL_NAME_UNIT = MODEL_NAME_UNIT;
exports.PATH_NAME_EVENT = PATH_NAME_EVENT;
exports.POPULATION_DEFAULT = POPULATION_DEFAULT;
exports.POPULATION_MAX_DEPTH = POPULATION_MAX_DEPTH;
exports.PREDEFINE_BUCKET_UNIT = PREDEFINE_BUCKET_UNIT;
exports.PREDEFINE_NAMESPACE_UNIT = PREDEFINE_NAMESPACE_UNIT;
